import { Money } from 'src/shared/domain/entities/value-objects';
import type { Status } from 'src/shared/domain/types';
import { EnrollmentType } from '../interfaces';
import { InvalidBookingStopError } from './errors/booking.errors';

/**
 * Shape of a booking entity as received by the constructor.
 *
 * Used both by {@link Booking.create} (with optional timestamps) and
 * {@link Booking.restore} (with all fields populated).
 */
export interface BookingProps {
  readonly id: string;
  readonly organizationId: string;
  readonly userId: string;
  readonly tripInstanceId: string;
  enrollmentDate: Date;
  status: Status;
  presenceConfirmed: boolean;
  enrollmentType: EnrollmentType;
  recordedPrice: Money;
  boardingStop: string;
  alightingStop: string;
  readonly createdAt?: Date;
  updatedAt?: Date;
}

/** @internal Normalised internal state after the constructor runs. All fields are present. */
interface BookingState {
  readonly id: string;
  readonly organizationId: string;
  readonly userId: string;
  readonly tripInstanceId: string;
  enrollmentDate: Date;
  status: Status;
  presenceConfirmed: boolean;
  enrollmentType: EnrollmentType;
  recordedPrice: Money;
  boardingStop: string;
  alightingStop: string;
  readonly createdAt: Date;
  updatedAt: Date;
}

/**
 * Domain aggregate root representing a passenger's reservation (enrollment) for a
 * specific {@link TripInstance}.
 *
 * Responsibilities:
 * - Record the price at the time of booking (price snapshot, never mutated after creation)
 * - Validate boarding/alighting stop invariants via {@link Booking.validateStops}
 * - Manage presence confirmation and cancellation lifecycle
 *
 * @remarks
 * The entity maps to the `enrollment` Prisma table. The `id` is a UUID generated by
 * `crypto.randomUUID()` in the domain layer before any database interaction.
 *
 * @see BookingProps
 * @see EnrollmentType
 */
export class Booking {
  private readonly props: BookingState;

  private constructor(props: BookingProps) {
    const now = new Date();

    this.props = {
      ...props,
      boardingStop: props.boardingStop.trim(),
      alightingStop: props.alightingStop.trim(),
      createdAt: props.createdAt ?? now,
      updatedAt: props.updatedAt ?? now,
    };
  }

  /**
   * Creates a new booking, running domain invariant checks on stops.
   *
   * Sets `status = ACTIVE`, `presenceConfirmed = false`, `enrollmentDate = now`,
   * and generates a UUID via `crypto.randomUUID()`.
   *
   * @param props - Booking data without `id`, `createdAt`, `updatedAt`, `status`,
   *   `presenceConfirmed`, or `enrollmentDate` (all set automatically)
   * @returns A new {@link Booking} instance ready to be persisted
   * @throws {@link InvalidBookingStopError} if `boardingStop` or `alightingStop` are empty or equal
   */
  static create(
    props: Omit<
      BookingProps,
      | 'id'
      | 'createdAt'
      | 'updatedAt'
      | 'status'
      | 'presenceConfirmed'
      | 'enrollmentDate'
    >,
  ): Booking {
    Booking.validateStops(props.boardingStop, props.alightingStop);

    return new Booking({
      ...props,
      id: crypto.randomUUID(),
      status: 'ACTIVE',
      presenceConfirmed: false,
      enrollmentDate: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  /**
   * Reconstructs a booking entity from a persisted database record.
   *
   * Skips invariant validation — the data is assumed to be already valid
   * since it was persisted through {@link Booking.create}.
   *
   * Intended for **exclusive** use by the infrastructure mapper.
   *
   * @param props - Complete state as returned by the database
   * @returns A {@link Booking} instance that mirrors the stored state
   */
  static restore(props: BookingProps): Booking {
    return new Booking(props);
  }

  /**
   * Validates that both stops are non-empty strings and that they are different.
   *
   * @param boarding - The boarding stop identifier
   * @param alighting - The alighting stop identifier
   * @throws {@link InvalidBookingStopError} if either stop is empty or both are equal
   */
  private static validateStops(boarding: string, alighting: string): void {
    if (!boarding.trim()) {
      throw new InvalidBookingStopError('boardingStop cannot be empty');
    }
    if (!alighting.trim()) {
      throw new InvalidBookingStopError('alightingStop cannot be empty');
    }
    if (boarding.trim() === alighting.trim()) {
      throw new InvalidBookingStopError(
        'boardingStop and alightingStop must be different',
      );
    }
  }

  /**
   * Marks the passenger's physical presence as confirmed.
   * Updates `updatedAt` to the current timestamp.
   *
   * @remarks
   * Only organisation members (Admin/Driver) should call this through
   * {@link ConfirmPresenceUseCase}. The passenger cannot confirm themselves.
   */
  confirmPresence(): void {
    this.props.presenceConfirmed = true;
    this.props.updatedAt = new Date();
  }

  /**
   * Soft-cancels the booking by setting `status = INACTIVE`.
   * Updates `updatedAt` to the current timestamp.
   *
   * @remarks
   * Guard logic (deadline check, trip status check) is enforced
   * at the {@link CancelBookingUseCase} level, not here.
   */
  cancel(): void {
    this.props.status = 'INACTIVE';
    this.props.updatedAt = new Date();
  }

  get id(): string {
    return this.props.id;
  }
  get organizationId(): string {
    return this.props.organizationId;
  }
  get userId(): string {
    return this.props.userId;
  }
  get tripInstanceId(): string {
    return this.props.tripInstanceId;
  }
  get enrollmentDate(): Date {
    return this.props.enrollmentDate;
  }
  get status(): Status {
    return this.props.status;
  }
  get presenceConfirmed(): boolean {
    return this.props.presenceConfirmed;
  }
  get enrollmentType(): EnrollmentType {
    return this.props.enrollmentType;
  }
  get recordedPrice(): Money {
    return this.props.recordedPrice;
  }
  get boardingStop(): string {
    return this.props.boardingStop;
  }
  get alightingStop(): string {
    return this.props.alightingStop;
  }
  get createdAt(): Date {
    return this.props.createdAt;
  }
  get updatedAt(): Date {
    return this.props.updatedAt;
  }
}
